version: 1.0.{build}

environment:
  matrix:
  - COMPILER: gcc
    PLATFORM: mingw64

install:
  - call %APPVEYOR_BUILD_FOLDER%\install_mingw.bat
  
build_script:
  - call %APPVEYOR_BUILD_FOLDER%\build_script_mingw.bat

after_build:
  - call %APPVEYOR_BUILD_FOLDER%\after_build_mingw.bat

test_script:
  - 'echo skip test'
  
artifacts:
  - path: swift.zip
    name: SWIFT
